# Generated by Django 3.1.2 on 2020-12-03 18:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cardno', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999)])),
                ('securityCode', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('expmo', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(12)])),
                ('expday', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(31)])),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetOne', models.CharField(max_length=100)),
                ('streetTwo', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=16)),
                ('zipcode', models.CharField(max_length=5)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
