# Generated by Django 3.1.2 on 2020-12-03 22:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('homeStreetOne', models.CharField(max_length=100)),
                ('homeStreetTwo', models.CharField(max_length=100)),
                ('homeCity', models.CharField(max_length=100)),
                ('homeState', models.CharField(max_length=100)),
                ('homeZipCode', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
