# Generated by Django 3.1.1 on 2020-09-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200904_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ante eros, tincidunt vitae tellus quis, euismod pharetra felis. Maecenas quis nulla ut augue feugiat facilisis. Sed blandit urna in nisi consequat finibus. Mauris scelerisque, arcu eu mattis laoreet, nunc leo elementum nisi, non euismod neque dolor nec nibh. Etiam et nisi ut turpis efficitur ornare in ac dolor. Maecenas ac aliquet lorem. Aliquam ut rhoncus ante. Nunc suscipit ante magna, porta venenatis arcu dictum ac. Nam posuere massa non aliquet auctor. Nulla dapibus metus quam, eu cursus mauris bibendum in. Duis ipsum augue, gravida vitae mi sed, convallis pellentesque est. Vestibulum a hendrerit dui, sed placerat ante. Nunc tristique, mi ut feugiat facilisis, libero tellus egestas diam, vel vestibulum lorem lorem quis eros. Donec vitae felis sed justo volutpat pulvinar.', max_length=1000),
            preserve_default=False,
        ),
    ]
