# Generated by Django 3.1.1 on 2020-11-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200919_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
